#!/usr/bin/env python

from pathlib import Path

from spacy_huggingface_hub import push  # type: ignore

project_dir = Path(__file__).parent
packages_dir = project_dir / "packages"

ns = "zentrum-lexikographie"

for whl in packages_dir.rglob("*.whl"):
    push(whl.as_posix(), namespace=ns)
