title: "de-hdt-wikiner"
description: >
  This project trains a part-of-speech tagger, morphologizer,
  lemmatizer, dependency parser and NER tagger from the German UD-HDT
  and WikiNER corpus.  It takes care of data preparation, converting
  it to spaCy's format, training separate models for GPU (-dist) and
  CPU (-lg) architectures, as well as evaluating the trained
  models. Note that multi-word tokens will be merged together when the
  corpus is converted since spaCy does not support multi-word token
  expansion.

directories:
  - "assets"
  - "configs"
  - "corpus"
  - "training"
  - "metrics"
  - "packages"

assets:
  - dest: "assets/ud-german-hdt.tar.gz"
    url: "https://codeload.github.com/UniversalDependencies/UD_German-HDT/tar.gz/refs/tags/r2.15"
  - dest: "assets/wikiner-de.bz2"
    url: "https://github.com/dice-group/FOX/raw/refs/tags/v2.3.0/input/Wikiner/aij-wikiner-de-wp3.bz2"

workflows:
  all:
    - preprocess
    - train

commands:
  - name: preprocess
    help: "Convert the corpus data to spaCy's format"
    script:
      - ./preprocess
    deps:
      - "assets/ud-german-hdt.tar.gz"
      - "assets/wikiner-de.bz2"
    outputs:
      - "corpus/ud-german-hdt/train.spacy"
      - "corpus/ud-german-hdt/dev.spacy"
      - "corpus/ud-german-hdt/test.spacy"
      - "corpus/wikiner-de/train.spacy"
      - "corpus/wikiner-de/dev.spacy"
      - "corpus/wikiner-de/test.spacy"
  - name: train
    help: "Train models."
    script:
      - ./train
    deps:
      - "configs/hdt-lg.cfg"
      - "configs/hdt-dist.cfg"
      - "configs/wikiner-lg.cfg"
      - "configs/wikiner-dist.cfg"
      - "corpus/ud-german-hdt/train.spacy"
      - "corpus/ud-german-hdt/dev.spacy"
      - "corpus/ud-german-hdt/test.spacy"
      - "corpus/wikiner-de/train.spacy"
      - "corpus/wikiner-de/dev.spacy"
      - "corpus/wikiner-de/test.spacy"
    outputs_no_cache:
      - "packages/de_hdt_lg/dist/de_hdt_lg.tar.gz"
      - "packages/de_hdt_dist/dist/de_hdt_dist.tar.gz"
      - "packages/de_wikiner_lg/dist/de_wikiner_lg.tar.gz"
      - "packages/de_wikiner_dist/dist/de_wikiner_dist.tar.gz"
  - name: clean
    help: "Remove intermediate files"
    script:
      - "rm -rf configs/filled"
      - "rm -rf corpus/"
      - "rm -rf metrics/"
      - "rm -rf training/"
      - "rm -rf packages/"
