name: test
on:
  pull_request:
    branches-ignore:
      - release-please*
  push:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
